### ISSUE TITLE
will this autoupdate?

### ISSUE THREAD

**Issue by majidaldo** [conda-forge/r-quarto-feedstock#5]
### Comment:

i had to install quarto with their system installer :( to get the latest version; 1.4.8. it had a fix. the version here is 1.2.

**Comment by dpryan79** [comment]
Since we pull from CRAN and the most recent version there is 1.2 that's kind of expected. I presume they don't expect anyone to be using anything after that.

**Comment by majidaldo** [comment]
Hmm. Well I guess posit builds are not synchronized.
